management:
  endpoints:
    web:
      base-path: /info
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        formate_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testing?serverTimezone=UTC
    username: root
    password: root
